### ISSUE TITLE
Scoped variables outside of functions translate to different code.

### ISSUE THREAD

**Issue by radiosilence** [js2coffee/js2coffee#219]
Take this:

    var x = "poop";
    var dorp = function() {
        var y = x;
        var x = "parp";
        console.log("inner x:", x);
        console.log('inner y:', y);
    }

    dorp();
    console.log("outer x:", x);

If you JS->CS then run the compiled CoffeeScript, you get an entirely different output:

    var dorp, x;

    x = "poop";

    dorp = function() {
      var y;
      y = x;
      x = "parp";
      console.log("inner x:", x);
      return console.log("inner y:", y);
    };

    dorp();

    console.log("outer x:", x);

**Comment by rstacruz** [comment]
The new version partially fixes this, and even adds a warning to show you what's going on:

![pasted_image_1_24_15__7_08_pm](https://cloud.githubusercontent.com/assets/74385/5887152/6e7b4284-a3fc-11e4-976e-8ba023642d80.png)

http://js2coffee.github.io/js2coffee-redux/

**Comment by timaschew** [comment]
nice :+1:

**Comment by pronebird** [comment]
This is very cool!

**Comment by rstacruz** [comment]
[fixed in v2.0.0](http://js2coffee.github.io/js2coffee-redux/#try:var%20x%20%3D%20%22poop%22%3B%0Avar%20dorp%20%3D%20function%28%29%20{%0A%20%20%20%20var%20y%20%3D%20x%3B%0A%20%20%20%20var%20x%20%3D%20%22parp%22%3B%0A%20%20%20%20console.log%28%22inner%20x%3A%22%2C%20x%29%3B%0A%20%20%20%20console.log%28%27inner%20y%3A%27%2C%20y%29%3B%0A}%0A%0Adorp%28%29%3B%0Aconsole.log%28%22outer%20x%3A%22%2C%20x%29%3B)
