### ISSUE TITLE
cannot avoid returning 'then' part of switch if it's the last statement in a function

### ISSUE THREAD

**Issue by timaschew** [js2coffee/js2coffee#250]
from #168 
> Still doesn't completely solve the problem when a function ends with a switch statement.

```
foobar = function(callback) {
  var x;
  x = "foo";
  switch (a) {
    case 1:
       "1"; break;
    case 2:
       "2"; break;
    default:
       "default";break;
  }
};
```
result:

```
foobar = (callback) ->
  x = undefined
  x = "foo"
  switch a
    when 1
      "1"
    when 2
      "2"
    else
      "default"
```

expected:
```
foobar = (callback) ->
  x = undefined
  x = "foo"
  switch a
    when 1
      "1"
    when 2
      "2"
    else
      "default"
  return
```

**Comment by rstacruz** [comment]
Fixed in 2.0. [demo](http://js2.coffee/#try:var%20foobar%20%3D%20function%28%29%20{%0A%20%20switch%20%28a%29%20{%0A%20%20%20%20case%201%3A%0A%20%20%20%20%20%20%20%221%22%3B%20break%3B%0A%20%20%20%20case%202%3A%0A%20%20%20%20%20%20%20%222%22%3B%20break%3B%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20%20%22default%22%3Bbreak%3B%0A%20%20}%0A}%3B)
