### ISSUE TITLE
convertion missing return

### ISSUE THREAD

**Issue by kngchn** [js2coffee/js2coffee#287]
when i converted this piece of script below: 
```
function series(item) {
  if(item) {
    async( item, function(result) {
      results.push(result);
      return series(items.shift());
    });
  } else {
    return final();
  }
}
```
on the website http://js2coffee.org/ , it produced below:
```
series = (item) ->
  if item
    async item, (result) ->
      results.push result
      series items.shift()

  else
    final()
  return
```
but it would not equal if you converted it back to js, the coffeescript should be
```
series = (item) ->
  if item
    async item, (result) ->
      results.push result
      series items.shift()

  else
    return final()
  return
```
sorry for my poor english and hope you will fix it.

**Comment by rstacruz** [comment]
Fixed in the upcoming 2.0 (js2coffee-redux). [Demo](http://js2coffee.github.io/js2coffee-redux/#try:function%20series%28item%29%20{%0A%20%20if%28item%29%20{%0A%20%20%20%20async%28%20item%2C%20function%28result%29%20{%0A%20%20%20%20%20%20results.push%28result%29%3B%0A%20%20%20%20%20%20return%20series%28items.shift%28%29%29%3B%0A%20%20%20%20}%29%3B%0A%20%20}%20else%20{%0A%20%20%20%20return%20final%28%29%3B%0A%20%20}%0A})
