### ISSUE TITLE
Node.js Futures functions won't compile from JS

### ISSUE THREAD

**Issue by fungilation** [js2coffee/js2coffee#325]
Sample code (from https://github.com/richsilv/meteor-cordova-notifications/blob/master/cordova-both.js):

``` javascript
fut = new Future();
function(err, res) {
    if (err) {
        fut.throw(err);
    } else {
        fut.return({
            response: res,
            userCount: regids.length
        });
    }
}
```

js2coffee error: "missing function identifier"

**Comment by rstacruz** [comment]
> js2coffee error: "missing function identifier"

This is actually a legit JS error because your function is missing a name (`function (err,res) {}` instead of `function name(err,res) {}`).

Go to your browsers console and try `function(){}`, you'll see what I mean.

Try wrapping it in parentheses. [demo](http://js2coffee.github.io/js2coffee-redux/#try:fut%20%3D%20new%20Future%28%29%3B%0A%28function%28err%2C%20res%29%20{%0A%20%20%20%20if%20%28err%29%20{%0A%20%20%20%20%20%20%20%20fut.throw%28err%29%3B%0A%20%20%20%20}%20else%20{%0A%20%20%20%20%20%20%20%20fut.return%28{%0A%20%20%20%20%20%20%20%20%20%20%20%20response%3A%20res%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20userCount%3A%20regids.length%0A%20%20%20%20%20%20%20%20}%29%3B%0A%20%20%20%20}%0A}%29)

**Comment by flying-sheep** [comment]
you probably missed that i discovered that  [in this comment](https://github.com/js2coffee/js2coffee/issues/325#issuecomment-65629125).

as said, it’s a fix of #157, which is fixed in redux.

**Comment by rstacruz** [comment]
Ah, oops :)
